### ISSUE TITLE
Soap Fault Could not connect to host 

### ISSUE THREAD

**Issue by Pappmann** [sjau/le2ispc#10]
after running "le2ispc domain.tld" i become following error (connection parameters in le2ispc.conf.php are correct): 

"PHP Fatal error:  Uncaught SoapFault exception: [HTTP] Could not connect to host in /root/le2ispc/le2ispc:268
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'https://ispc.do...', 'https://ispc.do...', 1, 0)
#1 /root/le2ispc/le2ispc(268): SoapClient->__call('login', Array)
#2 /root/le2ispc/le2ispc(268): SoapClient->login('letsencrypt', 'letsencrypt')
#3 /root/le2ispc/le2ispc(201): loadDomainData(Array, Object(SoapClient), '37')
#4 {main}
  thrown in /root/le2ispc/le2ispc on line 268"

when i running with "-n" all is fine, i canot make new requests now because auf cert rate limit.

**Comment by wzurborg** [comment]
Hi Pappmann, you are using the default settings for the ISPC host. You have to edit the hostname here:

```
$server["soap_uri"]     = "https://ispc.domain.tld:8080/remote/";
```
Change this to the URL your ISPC is running on, or change it to localhost:
```
$server["soap_uri"]     = "https://localhost:8080/remote/";
```

**Comment by Pappmann** [comment]
Hello,

i tried it with 
$server["soap_uri"]     = "https://localhost:8080/remote/";
and
$server["soap_uri"]     = "https://127.0.0.1:8080/remote/";
always the same error.

the server url is right, because im using a working roundcube ispconfig plugin, with the same parameter, only with a differned remote user.

**Comment by wzurborg** [comment]
Can you do this on your server:
```
telnet localhost 8080
```
It should give:
```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```
Then you are sure that ISPC is listening on port 8080. If not, then you might be using a different port.

**Comment by Pappmann** [comment]
~/le2ispc# telnet localhost 8080
Trying ::1...
Connected to localhost.
Escape character is '^]'.

**Comment by wzurborg** [comment]
Yes, you are still trying to connect to ```https://ispc.domain.tld:8080/remote/```, so your modified config file is not included. Check the correct path: ```/root/.le2ispc/le2ispc.conf.php``` - perhaps you omitted the dot?

**Comment by Pappmann** [comment]
ups, u are right, the missing dot was the problem....but i can test it next week.

Thanks.

**Comment by sjau** [comment]
Changed default soap_url to localhost. That should fix it.

https://github.com/sjau/le2ispc/commit/96dcad223b874a7802095b810485b4af09ece1ad
