### ISSUE TITLE
webroot parametr

### ISSUE THREAD

**Issue by stenlyk** [sjau/le2ispc#13]
Hi I just try your script and ends on this line
[https://github.com/sjau/le2ispc/blob/master/le2ispc#L185](https://github.com/sjau/le2ispc/blob/master/le2ispc#L185)

Should be there webroot of domain like (/var/www/domain.ltd/web) not just /var/www? 
Or where is the magic?

**Comment by sjau** [comment]
/var/www is fine since you make an alias on apache on lines 109-115, 120-127

not really sure how nginx works.

**Comment by stenlyk** [comment]
Ok nginx have alias to but for some security reason I'm not able to make this wokk on /var/www/ but it works on /usr/share/ do you want pull request with this change?

**Comment by sjau** [comment]
How would that be a security reason?

Anyway, I made webroot now configurable for apache. Feel free to provide a pull request to do the same for nginx.

**Comment by dmz006** [comment]
I can make a pull but I just made the following change around line 358:
# Run letsencrypt to create the certs;  --agree-eula is on current git (no Beta Testing) not required
echo "- Run Let's Encrypt Tool\n";
#$webroot = "/var/www/";
$webroot = "/var/www/$domain/web";

This way you don't need the alias, it will write the stuff into the domain being setup .well-known folder and "just work". At least it's worked for 2 domains I've setup so far.

**Comment by sjau** [comment]
well, that works also. However the beauty of the alias is that there aren't suddenly new folder for the end user. I think this can be closed.
