### ISSUE TITLE
Folder does not exists

### ISSUE THREAD

**Issue by enake** [sjau/le2ispc#4]
On my configuration, folder
/etc/apache2/conf-available does not exists so the script exits with
PHP Warning:  fopen(/etc/apache2/conf-available/letsencrypt-webroot.conf): failed to open stream: No such file or directory in /root/le2ispc on line 112
Unable to open file!

**Comment by sjau** [comment]
Are you using Apache 2.4?

**Comment by enake** [comment]
No, I'm using Apache/2.2.22 (Debian)

**Comment by sjau** [comment]
That's why, config changed. Debian Wheezy ships 2.4. I'll adjust it for 2.2 also :)

**Comment by wzurborg** [comment]
You can remove all apache handling anyway, the LE client installs the challenge into the webroot automatically. Since my fix with the L redirection it does it correctly for all my domains. No need to have an extra apache conf file.

**Comment by sjau** [comment]
wzuorborg: feel free to modify the apache stuff :) also I'm curious what implementation for the .htaccess you would employ. I noticed several .htaccess on my server that interfere with LE hence the reason for integrating the renaming and restoring and it's optional to do so.

**Comment by wzurborg** [comment]
I think we are mixing two different approaches:

1. Use an Apache conf file to redirect all LE requests for the challenge to a unique location. This requires to supply a common webroot for all domains, e.g. _--webroot /var/www_.

2. Read the configured webroot for each domain from ISPConfig and use that for the _-webroot_ argument.

I would prefer no. 1 but the problem is how to find the Apache conf directory for the different versions. That's why I use no. 2 at the moment, but it would not work for certain types of redirection. Not sure how to proceed from here.

**Comment by wzurborg** [comment]
I have switched to option 1 now, but this only works for Apache 2.4.8 and later. The strategy is to specify a common webroot for all domains and to rewrite the ACME challenge request to that location. My config file _/etc/apache2/conf-available/letsencrypt.conf_ now looks as follows:
```
<IfModule mod_headers.c>
    <LocationMatch "/.well-known/acme-challenge/*">
        Header set Content-Type "text/plain"
    </LocationMatch>
</IfModule>

# Rewrite LetsEncrypt challenge request
RewriteEngine on
RewriteRule (\.well-known/acme-challenge/.*)$ /var/www/$1 [L]
RewriteOptions InheritDownBefore
```

**This works for Apache 2.4.8 and greater only!**

Advantages:

* It works independent of any further redirections in _.htaccess_ or wherever. No need to save and restore _.htaccess_.
* No need to extract the webroot from the ISPConfig DB, the _--webroot-path_ argument is fixed to _/var/www_.

I do not want to overwrite your script, so I will commit this to my own repo only. Will take some time though.

**Comment by sjau** [comment]
actually, having a global .well-known folder makes sense. I have already done so for my /horde stuff which works on Apache 2.2 and 2.4 I think.

See lines 423-437 here:  https://github.com/sjau/perfectDebian/blob/master/install.sh#L423

Btw, also splitting up conf and main script and having conf in /root/.le2ispc/le2ispc.conf.php

I'll probably make a commit later on.

**Comment by wzurborg** [comment]
We should also rename the word "subdomains" to "alternate domains", because you can specify any other domains that will go into the same certificate as alternate names.

**Comment by sjau** [comment]
@wzurborg 

I tried your conf settings and I can't get it to work

**Comment by sjau** [comment]
So, I think I have now some config for webroot challenge working for 2.2 and 2.4 -> https://github.com/sjau/le2ispc/commit/25d557b2db56561443997dbd97a19693b8b7dd03#diff-37f0563f7e9189b7d7ce91c9265437f5
