### ISSUE TITLE
PHP Fatal error:  Uncaught SoapFault exception: [Client] looks like we got no XML document in /root/letsencrypt/le2ispc/le2ispc:302

### ISSUE THREAD

**Issue by Thumpxr** [sjau/le2ispc#7]
Those are the output lines i get:

1. Get the domain name.
2. Query MySQL whether it's a vhost.
3. Prepare Server for webroot authentication.
4. Create folder in web root for acme-challenge
5. Disable temporarily the .htaccess file in webroot (apache only).
6. Run Let's Encrypt Tool
7. Restore .htaccess again (apache only).
8. Read SSL info into vars.
9. Insert SSL info via API.
PHP Fatal error:  Uncaught SoapFault exception: [Client] looks like we got no XML document in /root/letsencrypt/le2ispc/le2ispc:302
Stack trace:
#0 /root/letsencrypt/le2ispc/le2ispc(302): SoapClient->__call('sites_web_domai...', Array)
#1 /root/letsencrypt/le2ispc/le2ispc(302): SoapClient->sites_web_domain_update('7f2cbf14e4f7e72...', '1', '1', Array)
#2 /root/letsencrypt/le2ispc/le2ispc(251): saveDomainData(Array, Object(SoapClient), '1', '1', Array)
#3 {main}
  thrown in /root/letsencrypt/le2ispc/le2ispc on line 302

**Comment by wzurborg** [comment]
Did you create your remote user in ISPConfig as per README file?

**Comment by Thumpxr** [comment]
Yes i did.

**Comment by wzurborg** [comment]
... and set it into the header section of le2ispc:
```
$server["username"]     = "user";
$server["password"]     = "password";
```

**Comment by Thumpxr** [comment]
I did this aswell. Just verified, that both user and password are identical.

**Comment by sjau** [comment]
Can you make a screenshot of the settings for the remote user? Which permission that user has?

**Comment by Thumpxr** [comment]
He has those permissions:

Webseiten Domain FunktionenWebseiten Aliasdomain FunktionenWebseiten Subdomain Funktionen
Funktionen = functionsWebseiten = website
Date: Wed, 9 Dec 2015 03:54:16 -0800

**Comment by sjau** [comment]
Can you retry with newest version?

**Comment by sjau** [comment]
were you successful with the newest version?

**Comment by Thumpxr** [comment]
Yes





On Wed, Dec 23, 2015 at 12:57 AM -0800, "sjau" <notifications@github.com> wrote:





were you successful with the newest version?

---

**Comment by sjau** [comment]
good to know. No idea what that error appeared :)
