### ISSUE TITLE
--webroot-path every time /var/www

### ISSUE THREAD

**Issue by dabonzo** [sjau/le2ispc#8]
When I run le2ispc www.example.com there should be --webroot-path /var/www/exapmle.com/web or something like that.Everytime I get --webroot-path /var/www/, though.
That results in the LE error  "Error: The client lacks sufficient authorization" and termination of the script.
AN older version with the right webroot-path works as supposed

**Comment by wzurborg** [comment]
The webroot-path /var/www is correct if you install the correcsponding Apache config, as described in my posting in issue https://github.com/sjau/le2ispc/issues/4.

I have not got around to push this solution. Of course a mixture of approaches will not work.

**Comment by sjau** [comment]
the apache config should be installed when the script is run. Can you check your apache conf.d or conf-enabled folders and check if there's a webroot-le file?

**Comment by dabonzo** [comment]
There is the webroot file, but this part
 $txt = '
            RewriteEngine On
            Alias /.well-known /var/www/.well-known
            <Directory /var/www/.well-known>
                Options +FollowSymLinks
                AllowOverride All
                Require all granted
            </Directory>
        ';
is missed. I'll look at wzurborg psot, didn't read it

**Comment by sjau** [comment]
if you have that webroot file, then you could add the contents manually.

Apache 2.4

```
RewriteEngine On
Alias /.well-known /var/www/.well-known

Options +FollowSymLinks
AllowOverride All
Require all granted
```

**Comment by dabonzo** [comment]
I reviewed the code and the first problem was I had some old code in letsencrypt-webbroot.conf in conf.d (I use apache 2.2 on Debian Wheezy). There is only a check if file exists but not whats the content of the file. If you use a new version of your script and change stuff what schould be writtten in the letsencrypt-webroot.conf, this stuff will not be written into the file because the file exists already. Maybe deletion and new creation would be better.

Second problem I ran into is that a2enconf and systemctl don't exist on Debian wheezy. I suppose on apache 2.2 you don't need a2enconf because all conf file inside conf.d are read via httpd.conf. But also, that does not solve the problem. Unfortunately the script does not work for me with apache2.2 on Debian Wheezy. I'll try some things and let you know. 

A third potential problem could also be caused by mixing script version. 
If you use an old version, .well-know is written into the actual webroot. Using a new version .well-known is global. I don't know the precedence but it could cause problems with renewal if you created the cert with an older version and renewal with a new version because you have .well-known in /var/www and the acutual webroot of the domain

**Comment by wzurborg** [comment]
Well, at least your third point is not a problem. The LE server just send a HTTP challenge to your URL and expect the correct reply. The webroot is only significant for the LE client, and it can be anywhere. You only need to make sure that Apache finds it where the client has put it.

**Comment by dabonzo** [comment]
After further inspection I found the problem. You should do a check before providing the $txt variable with the content of the letsencrypt-webroot.conf file. "Require all granted" directive is not available in apache 2.2. Also, if letsencrypt-webroot already exists (possibly with content from some other le2ispc-version) this file will not be touched and go on with the old conten. Quick, dirty solution could be delete the file and recreate.  Created a quick pull-request for the $txt-part

**Comment by sjau** [comment]
well, in current system you can define if it's apache 2.2 or apache 2.4 and different files are being written.

**Comment by sjau** [comment]
Ok, I did add the check for apache 2.2/2.4 but didn't alter the according config that should be written. My bad.
